-- Add FPT admin user with email admin@fpt.edu.vn
-- Password: admin123
-- Hash generated by BCrypt (cost 10)

DO $$
DECLARE
    admin_role_id BIGINT;
BEGIN
    -- Get admin role ID
    SELECT role_id INTO admin_role_id FROM roles WHERE role_name = 'ADMIN' LIMIT 1;
    
    IF admin_role_id IS NOT NULL THEN
        -- Insert FPT admin user if not exists
        INSERT INTO users (full_name, email, password_hash, role_id, status)
        SELECT 'FPT Admin', 'admin@fpt.edu.vn', '$2a$10$7mDvM3yB9QwUQLS1V1lYge5lZ7m5Wm7s0w8O5n2qv3f3pJ4t9nVbS', admin_role_id, TRUE
        WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@fpt.edu.vn');
    END IF;
END $$;
