-- Create an initial admin user with a pre-hashed password (BCrypt)
-- Password: admin123
-- Hash below generated by BCrypt (cost 10)

DO $$
DECLARE
    admin_role_id BIGINT;
BEGIN
    SELECT role_id INTO admin_role_id FROM roles WHERE role_name = 'ADMIN' LIMIT 1;
    IF admin_role_id IS NOT NULL THEN
        INSERT INTO users (full_name, email, password_hash, role_id, status)
        SELECT 'Admin', 'admin@unilab.local', '$2a$10$7mDvM3yB9QwUQLS1V1lYge5lZ7m5Wm7s0w8O5n2qv3f3pJ4t9nVbS', admin_role_id, TRUE
        WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@unilab.local');
    END IF;
END $$;


